label: 'Modereret indhold'
display:
  default:
    display_title: Standard
    display_options:
      title: 'Modereret indhold'
      fields:
        title:
          label: Titel
          separator: ', '
        type:
          label: Indholdstype
          separator: ', '
        name:
          label: Forfatter
          separator: ', '
        moderation_state:
          label: Godkendelsestilstand
          separator: ', '
        changed:
          label: Opdateret
          separator: ', '
        operations:
          label: Handlinger
      pager:
        options:
          tags:
            next: 'Næste ›'
            previous: '‹ Forrige'
            first: '« Første'
            last: 'Sidste »'
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Indholdstype
        moderation_state:
          expose:
            label: Godkendelsestilstand
        langcode:
          expose:
            label: Sprog
  moderated_content:
    display_title: 'Modereret indhold'
