_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: da
uuid: bae67e87-b92d-480b-986a-e42f918fe5a3
name: Kragebækgård
mail: paddy@deburca.org
slogan: ''
page:
  403: /user/login
  404: ''
  front: /page/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: da
mail_notification: null
